# ms-config-server/src/main/resources/application.yml
server:
port: 8888

spring:
application:
name: ms-config-server
cloud:
config:
server:
git:
uri: https://github.com/fransasdsa/examen.git
clone-on-start: true

management:
endpoints:
web:
exposure:
include: "*"
