server:
  port: 8888
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fransasdsa/examen.git
          searchPaths: config-data
          clone-on-start: true


  security:
    user:
      name: root
      password: 123456
