# ms-student-service/src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: ms-student-service

  datasource:
    url: jdbc:mysql://localhost:3306/ms-student-service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
